<?php
/**
 * Plugin Name: Quote Exporter
 * Plugin URI: http://cedarwaters.com/
 * Description: This plugin exports quotes generated by quote management plugin.
 * Version: 1.0.0
 * Author: CedarWaters
 * Author URI: http://cedarwaters.com/
 */

date_default_timezone_set("America/Detroit");

define('QE_ROOT', dirname(__FILE__));
define('QE_URL', plugins_url('/', __FILE__));
define('QE_HOME', home_url('/'));

/*require_once( QE_ROOT . '/assets/Classes/PHPExcel.php');
require_once( QE_ROOT . '/assets/Classes/PHPExcel/Calculation.php');
require_once( QE_ROOT . '/assets/Classes/PHPExcel/Cell.php');*/

class QuoteExporter {
    /**
     * Constructor 
     */
    public function __construct() {
		add_action('admin_menu', array(&$this, 'qe_plug_page'));
    }
	
	public function qe_plug_page() {
		add_submenu_page( 'edit.php?post_type=quote', 'Export', 'Export', 'manage_options', 'qe-export', array(&$this, 'qe_settings_plug_page'));
	}

    /**
     * Plugins settings page
     */
    public function qe_settings_plug_page() {
		require_once( QE_ROOT . '/include/qe-settings.php');
	}			
}
// eof class
global $QuoteExporter;
$QuoteExporter = new QuoteExporter();